### ISSUE TITLE
Can you please help me how to run this on telegram web

### ISSUE THREAD

**Issue by Denis7637** [Galkurta/OKX-Racer-BOT#6]
I tried to run the web version in the telegraph, but I couldn't. Can you please tell me what you changed?

**Comment by Troxip** [comment]
Yeah, indeed that would be amazing if he learned us how to run tg apps on browser

**Comment by Troxip** [comment]
> I tried to run the web version in the telegraph, but I couldn't. Can you please tell me what you changed?

k = h && i
>
k = true

**Comment by Galkurta** [comment]
open okx racer on telegram web(use urban vpn if u cant open okx racer) > inspect > go to aplication > select session storage > select https://www.okx.com > select initparam then copy query_id

**Comment by Denis7637** [comment]
> > I tried to run the web version in the telegraph, but I couldn't. Can you please tell me what you changed?
> 
> k = h && i
> 
> > 
> 
> k = true

![image](https://github.com/user-attachments/assets/38a386fc-e623-4e83-b41a-df3fa89694f6)
I am use Resource Override to change headers but today its not help. Can you pls send photo what mean:
k = h && i

k = true

**Comment by Denis7637** [comment]
> open okx racer on telegram web(use urban vpn if u cant open okx racer) > inspect > go to aplication > select session storage > select https://www.okx.com > select initparam then copy query_id
Can you pls help I can't find "inspect"
